export * from './globalData';
export * from './simple-coin-data-res';
export * from './detailedCoinData';
export * from './coinsView';
export * from './fiatMap';
export * from './cryptoMap';
export * from './converterRes';
export * from './allCoins';
export * from './transaction';