export * from './global-data-res';
export * from './simple-coin-data-res';
export * from './detailed-coin-data-res';
export * from './coins-view-top-res';
export * from './coins-view-new-res';
export * from './fiat-map';
export * from './crypto-map';
export * from './converter-res';
export * from './all-coins-res';